TOPDIR = ..

include $(TOPDIR)/Preamble.make

SUBDIRS = blkid ocfs2interface

MANS = ocfs2console.8

SBIN_EXTRA = ocfs2console

DIST_FILES = ocfs2console ocfs2console.8.in

include $(TOPDIR)/Postamble.make
