#!/usr/bin/python

# XXX: for production
#!/usr/bin/python -W ignore::DeprecationWarning

from ocfs2interface.about import process_args
clusterconf = process_args()

try:
    import gtk
except RuntimeError:
    import sys
    print >>sys.stderr, '''ERROR: ocfs2console needs an X11 display.
Make sure a proper setup for your display environment exists.\n'''
    sys.exit(1)

if clusterconf:
    from ocfs2interface.clconfig import cluster_configurator
    cluster_configurator()
else:
    from ocfs2interface.console import main
    main()
