#!/usr/bin/python

# XXX: for production
#!/usr/bin/python -W ignore::DeprecationWarning

from ocfs2console.about import process_info_args
process_info_args()

from ocfs2console.interface import main
main()
