.TH "mount.ocfs2" "8" "May 2006" "Version 1.2.1" "OCFS2 Manual Pages"
.SH "NAME"
mount.ocfs2 \-  mount using the Oracle Cluster File System 2 (OCFS2)
.SH "SYNOPSIS"
\fBmount.ocfs2\fR [\fB\-vn\fR] [\fB\-o options\fR] [\fB\-t type\fR] \fIdevice\fR \fImount_point\fR
.SH "DESCRIPTION"
.PP 
\fBmount.ocfs2\fR is used to mount preformatted OCFS2 devices.
.SH "OPTIONS"
.TP
\fB\-v\fR
verbose.

.TP
\fB\-n\fR
nomtab.

.SH "BUGS"
Stuff.

.SH "SEE ALSO"
.BR mkfs.ocfs2(8)

.SH "AUTHORS"
Oracle Corporation

.SH "COPYRIGHT"
Copyright \(co 2002, 2004-2006 Oracle Corporation
